language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install document-your-code
# command to run tests
script:
  - pytest
  - black --check --diff --skip-string-normalization .
