language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PTYHON_VERSION == 3.6 ]]; pip install black; fi
  - pip install document-your-code
# command to run tests
script:
  - pytest
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; black --check --diff --skip-string-normalization .; fi
